baseURL: "https://www.geeqla.com"
title: Geeqla
paginate: 1
theme: PaperMod
disableHugoGeneratorInject: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: G-3DYJCT1PQ7
enableEmoji: true

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepComments: false
      keepConditionalComments: false
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepWhitespace: false

languages:
  en:
    languageName: ":gb:"
    languageAltTitle: "English" # added by Geeqla
    weight: 1
    description: "House of Geeqla on the Internet"
    author: Geeqla
    title: House of Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Hey!
      Content: >
        My [PGP key](https://geeq.la/@) is 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hey!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "My **[PGP key](https://geeq.la/@)** is 49FF57C32BD36752"        

  ru:
    languageName: ":ru:"
    languageAltTitle: "Русский" # added by Geeqla
    weight: 2
    description: "Дом Гикла в сети Интернет"
    author: Гикла
    title: Дом Гикла
    label:
      text: Гикла
    homeInfoParams:
      Title: Привет!
      Content: >
        Мой [ключ PGP](https://geeq.la/@) – 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Привет!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Мой **[ключ PGP](https://geeq.la/@)** – 49FF57C32BD36752"

  de:
    languageName: ":de:"
    languageAltTitle: "Deutsch" # added by Geeqla
    weight: 3
    description: "Das Haus von Geeqla im Internet"
    author: Geeqla
    title: Das Haus von Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Hallo!
      Content: >
        Mein [PGP-Schlüssel](https://geeq.la/@) ist 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hallo!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Mein **[PGP-Schlüssel](https://geeq.la/@)** ist 49FF57C32BD36752"

  fr:
    languageName: ":fr:"
    languageAltTitle: "Française" # added by Geeqla
    weight: 4
    description: "La maison de Geeqla sur le Web"
    author: Geeqla
    title: La maison de Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Salut!
      Content: >
        Ma [clé publique PGP](https://geeq.la/@) est 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Salut!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Ma **[clé publique PGP](https://geeq.la/@)** est 49FF57C32BD36752"

params:
  env: production
  defaultTheme: auto
  # disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  displayFullLangName: true
  launchYear: 2016 # added by Geeqla
  hideCredits: true # added by Geeqla
  images: ["website-cover.png"]
  socialIcons:
    - name: github
      url: "https://www.github.com/geeqla"
    - name: linkedin
      url: "https://www.linkedin.com/in/geeqla"
    - name: keybase
      url: "https://www.keybase.io/geeqla"
    - name: facebook
      url: "https://www.facebook.com/geeqla"
    - name: twitter
      url: "https://www.twitter.com/geeqla"
    - name: telegram
      url: "https://t.me/geeqla"
    - name: instagram
      url: "https://www.instagram.com/geeqla"
    - name: youtube
      url: "https://www.youtube.com/geeqla"

taxonomies:
  category: categories
  tag: tags
  series: series