baseURL: "https://www.geeqla.com"
title: Geeqla
paginate: 1
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-149650101-1
enableEmoji: true

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false

languages:
  en:
    languageName: ":gb:"
    languageAltTitle: "English" # added by Geeqla
    weight: 1
    description: "House of Geeqla"
    author: Geeqla
    title: House of Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Hey!
      Content: >
        My [PGP key](/geeqla.asc) is 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hey!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "My **[PGP key](/geeqla.asc)** is 49FF57C32BD36752"        

  ru:
    languageName: ":ru:"
    languageAltTitle: "Русский" # added by Geeqla
    weight: 2
    description: "Дом Гикла"
    author: Гикла
    title: Дом Гикла
    label:
      text: Гикла
    homeInfoParams:
      Title: Привет!
      Content: >
        Мой [ключ PGP](/geeqla.asc) – 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Привет!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Мой **[ключ PGP](/geeqla.asc)** – 49FF57C32BD36752"

  de:
    languageName: ":de:"
    languageAltTitle: "Deutsch" # added by Geeqla
    weight: 3
    description: "Das Haus von Geeqla"
    author: Geeqla
    title: Das Haus von Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Hallo!
      Content: >
        Mein [PGP-Schlüssel](/geeqla.asc) ist 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hallo!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Mein **[PGP-Schlüssel](/geeqla.asc)** ist 49FF57C32BD36752"

  fr:
    languageName: ":fr:"
    languageAltTitle: "Française" # added by Geeqla
    weight: 4
    description: "La maison de Geeqla"
    author: Geeqla
    title: La maison de Geeqla
    label:
      text: Geeqla
    homeInfoParams:
      Title: Salut!
      Content: >
        Ma [clé publique PGP](/geeqla.asc) est 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Salut!
      imageUrl: "/geeqla.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Ma **[clé publique PGP](/geeqla.asc)** est 49FF57C32BD36752"

params:
  env: production
  defaultTheme: auto
  # disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  displayFullLangName: true
  launchYear: 2016 # added by Geeqla
  hideCredits: true # added by Geeqla

  socialIcons:
    - name: github
      url: "https://www.github.com/geeqla"
    - name: linkedin
      url: "https://www.linkedin.com/in/geeqla"
    - name: keybase
      url: "https://www.keybase.io/geeqla"
    - name: twitter
      url: "https://www.twitter.com/geeqla"
    - name: telegram
      url: "https://t.me/geeqla"
    - name: instagram
      url: "https://www.instagram.com/geeqla"
    - name: youtube
      url: "https://www.youtube.com/geeqla"

taxonomies:
  category: categories
  tag: tags
  series: series