baseURL: "https://geeqla-dev.vercel.app"
title: Geeqla (dev)
paginate: 1
theme: hugo-PaperMod-develop
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-149650101-1
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: false

languages:
  en:
    languageName: ":gb:"
    languageNameFull: "English"
    weight: 1
    description: "Homepage of Geeqla"
    author: Geeqla
    homeInfoParams:
      Title: Hey!
      Content: >
        My [PGP key](/geeqla.asc) is 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hey!
      imageUrl: "/avatar.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "My **[PGP key](/geeqla.asc)** is 49FF57C32BD36752"        

  ru:
    languageName: ":ru:"
    languageNameFull: "Русский"
    weight: 2
    description: "Дом-страница Гиклы"
    author: Гикла
    title: Гикла
    homeInfoParams:
      Title: Привет!
      Content: >
        Мой [ключ PGP](/geeqla.asc) – 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Привет!
      imageUrl: "/avatar.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Мой **[ключ PGP](/geeqla.asc)** – 49FF57C32BD36752"

  de:
    languageName: ":de:"
    languageNameFull: "Deutsch"
    weight: 3
    description: "Homepage von Geeqla"
    author: Geeqla
    title: Geeqla
    homeInfoParams:
      Title: Hallo!
      Content: >
        Mein [PGP-Schlüssel](/geeqla.asc) ist 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Hallo!
      imageUrl: "/avatar.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Mein **[PGP-Schlüssel](/geeqla.asc)** ist 49FF57C32BD36752"

  fr:
    languageName: ":fr:"
    languageNameFull: "Française"
    weight: 4
    description: "Page d'accueil de Geeqla"
    author: Geeqla
    title: Geeqla
    homeInfoParams:
      Title: Salut!
      Content: >
        Ma [clé publique PGP](/geeqla.asc) est 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Salut!
      imageUrl: "/avatar.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "Ma **[clé publique PGP](/geeqla.asc)** est 49FF57C32BD36752"

  it:
    languageName: ":it:"
    languageNameFull: "Italiano"
    weight: 5
    description: "Homepage di Geeqla"
    author: Geeqla
    title: Geeqla
    homeInfoParams:
      Title: Ciao!
      Content: >
        La mia [chiave PGP](/geeqla.asc) è 49FF57C32BD36752
    profileMode:
      enabled: true
      title: Ciao!
      imageUrl: "/avatar.png"
      imageTitle: Geeqla
      imageWidth: 120
      imageHeight: 120
      subtitle: "La mia **[chiave PGP](/geeqla.asc)** è 49FF57C32BD36752"

params:
  env: development
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: false
  ShowShareButtons: false
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  socialIcons:
    - name: github
      url: "https://www.github.com/geeqla"
    - name: telegram
      url: "https://t.me/geeqla"
    - name: linkedin
      url: "https://www.linkedin.com/in/geeqla"
    - name: youtube
      url: "https://www.youtube.com/geeqla"
    - name: keybase
      url: "https://keybase.io/geeqla"
  # custom params
  hideCredits: true

taxonomies:
  category: categories
  tag: tags
  series: series