baseURL: "https://www.geeqla.ru"
title: Гикла
paginate: 1
theme: PaperMod
disableHugoGeneratorInject: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: G-9M3D5P4HZ2
enableEmoji: true
defaultcontentlanguage: ru
disableKinds: ["taxonomy"] # overrules and disables taxonomies at the bottom
ignoreErrors: ["error-disable-taxonomy"] # overrules and disables taxonomies at the bottom

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepComments: false
      keepConditionalComments: false
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepWhitespace: false

languages:
  ru:
    languageName: ":ru:"
    weight: 4
    author: Гикла
    title: Дом Гикла
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "Русский" # added by Geeqla
      description: "Дом Гикла в сети Интернет."
      label:
        text: Гикла
        iconHeight: 30
      homeInfoParams:
        Title: Привет!
        Content: >
          Мой [PGP ключ](https://geeq.la/@).
      profileMode:
        enabled: true
        title: Привет!
        imageUrl: "icon.svg"
        imageTitle: Geeqla
        imageWidth: 120
        imageHeight: 120
        subtitle: "Мой **[PGP ключ](https://geeq.la/@)**."

params:
  defaultTheme: auto
  # disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  displayFullLangName: true
  mirrorSite: "https://www.geeqla.com" # added by Geeqla
  mirrorSiteLang: "en" # added by Geeqla
  mirrorSiteLanguageName: ":gb:" # added by Geeqla
  mirrorSiteLanguageAltTitle: "English" # added by Geeqla
  launchYear: 2016 # added by Geeqla
  hideCredits: true # added by Geeqla
  yandexMetrika: 92131351 # added by Geeqla
  images: ["website-cover.png"]
  socialIcons:
    - name: github
      url: "https://www.github.com/geeqla"
    - name: linkedin
      url: "https://www.linkedin.com/in/geeqla"
    - name: keybase
      url: "https://keybase.io/geeqla"
    - name: telegram
      url: "https://t.me/geeqla"
    - name: vk
      url: "https://vk.com/geeqla"
    - name: youtube
      url: "https://www.youtube.com/geeqla"
  assets:
    disableHLJS: true # disables loading of highlight.js
    theme_color: "#000000"
    msapplication_TileColor: "#000000"

taxonomies:
  category: categories
  tag: tags
  series: series